set rtp+=~/.nix-profile/share/vim-plugins/*

color gruvbox
"
" Default Vim settings

" Key rebindings (try not to go overboard, need to be able to use vanilla vim)
" Discourage use of mouse and keyboard
set mouse=""
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

let mapleader=" "

" Colours
" Gruvbox setup (must be done before color set)
" https://github.com/morhetz/gruvbox
let g:gruvbox_italic=1
let g:gruvbox_contrast_dark='soft'
let g:gruvbox_contrast_light='soft'

" https://stackoverflow.com/a/5702498
try
    colorscheme gruvbox
catch /^Vim\%((\a\+)\)\=:E185/
    colorscheme desert
endtry

set background=dark
syntax on

" Code aesthetic
set nowrap
set list
set listchars=precedes:<,extends:>,tab:>.,trail:!
set cursorline
set showmatch
set textwidth=79
set titlestring=%r%m\ %t\ %y\ -\ VIM:\ the\ only\ text\ editor titlelen=80

" Line numbers
set number
set relativenumber

" Indentation
filetype plugin indent on
set backspace=indent,eol,start
set expandtab
set shiftwidth=4
set tabstop=4

" Always show status bar for airline
set laststatus=2
" Always show margin bar, otherwise LangClient makes text jump around
" while scrolling
set signcolumn=yes

" In-code auto-completion
" Use languageserver
set completefunc=LanguageClient#complete
" noinsert required for ncm2
set completeopt=menu,preview,noinsert,menuone,noselect

" Let's get wild!!~
" set wildignore+=*ios/*
" set wildignore+=*plugins*
" set wildignore+=*release*
set wildignore+=*android/*
set wildignore+=*target/*
set wildignore+=*bazel-*
set wildignore+=*coverage*
set wildignore+=*dist*,*dist-server*
set wildignore+=*DS_Store*
set wildignore+=*node_modules*
set wildignore+=*platforms*
set wildignore+=*sass-cache*
set wildignore=*.o,*.obj,*~,*.pyc
set wildmenu
set wildmode=longest,list:full

" Plugin-specific settings

" Language Client setup
" Enable ncm2 autocompletion everywhere
autocmd BufEnter  *  call ncm2#enable_for_buffer()

" Required for operations modifying multiple buffers like rename.
set hidden

let g:rooter_patterns = ['go.mod', 'WORKSPACE', '.git/', 'Cargo.toml']

let g:LanguageClient_serverCommands = {
    \   'rust': {
    \     'name': 'rust-analyzer',
    \     'command': ['rust-analyzer'],
    \     'initializationOptions': {
    \       'cargo': {
    \         'allFeatures': v:true,
    \         'unsetTest': ['cec-rs', 'cec_rs', 'cecd'],
    \       },
    \       'checkOnSave': {
    \         'allFeatures': v:true,
    \         'command': 'clippy',
    \       },
    \       'procMacro': {
    \         'enable': v:true,
    \       },
    \       'experimental': {
    \         'procAttrMacros': v:true,
    \       },
    \     },
    \   },
    \   'python': ['pylsp'],
    \ }
    " 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    " 'javascript.jsx': ['tcp://127.0.0.1:2089'],
    " 'python': ['/usr/local/bin/pyls'],
    " 'ruby': ['~/.rbenv/shims/solargraph', 'stdio'],

" let g:LanguageClient_loggingFile = '/tmp/LanguageClient.log'
" let g:LanguageClient_loggingLevel = 'INFO'
" let g:LanguageClient_serverStderr = '/tmp/LanguageServer.log'

" Airline setup
let g:airline#extensions#tabline#=1
let g:airline#extensions#tabline#enabled=1
let g:airline_interactive_collapse=1
let g:airline_powerline_fonts=1
let g:airline_theme='gruvbox'

" FZF Shortcut Bindings
nnoremap <leader>q :Rg<CR>
" nnoremap <leader>q :GFiles<CR>
nnoremap <leader>w :Files<CR>
nnoremap <leader>e :Buffers<CR>
nnoremap <leader>s :Lines<CR>
nnoremap <leader>d :BLines<CR>
nnoremap <leader>r :call LanguageClient#textDocument_rename()<CR>
nnoremap <leader>f :call LanguageClient#textDocument_formatting()<CR>
nnoremap <leader>c :call LanguageClient#explainErrorAtPoint()<CR>
nnoremap K :call LanguageClient#textDocument_hover()<CR>
nnoremap <leader><leader> :call LanguageClient#textDocument_definition()<CR>
nnoremap <leader>R :call LanguageClient#textDocument_references()<CR>
nnoremap <leader>z :call LanguageClient#textDocument_codeAction()<CR>
nnoremap <leader>x :call LanguageClient#workspace_executeCommand("Run")<CR>

" incsearch.vim keybindings
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
