ZSH=$HOME/.nix-profile/share/oh-my-zsh

if [[ -e "$ZSH/oh-my-zsh.sh" ]]
then
    # Set name of the theme to load.
    # Look in ~/.oh-my-zsh/themes/
    ZSH_THEME="steeef"

    # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
    # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
    plugins=(git rust)

    source $ZSH/oh-my-zsh.sh
fi
